const motivationalQuotes = [
    { text: "Consistência supera talento quando talento não é consistente.", author: "Anônimo" },
    { text: "O sucesso é a soma de pequenos esforços repetidos dia após dia.", author: "Robert Collier" },
    { text: "Acredite em si mesmo e tudo será possível.", author: "Anônimo" },
    { text: "Não espere por oportunidades, crie-as.", author: "Anônimo" },
    { text: "O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.", author: "Henry Ford" },
    { text: "A disciplina é a ponte entre metas e conquistas.", author: "Jim Rohn" },
    { text: "Cada dia é uma nova oportunidade para mudar sua vida.", author: "Anônimo" },
    { text: "Trabalhe duro em silêncio, deixe o sucesso fazer barulho.", author: "Frank Ocean" },
    { text: "A persistência é o caminho do êxito.", author: "Charles Chaplin" },
    { text: "Você é mais forte do que pensa.", author: "Anônimo" },
    { text: "Codificar é a linguagem do futuro.", author: "Anônimo" },
    { text: "O único modo de fazer um excelente trabalho é amar o que você faz.", author: "Steve Jobs" },
    { text: "Não pare até se orgulhar.", author: "Anônimo" },
    { text: "Seja a mudança que você deseja ver no mundo.", author: "Mahatma Gandhi" },
    { text: "Sua única limitação é você mesmo.", author: "Anônimo" },
    { text: "Grandes coisas nunca vêm de zonas de conforto.", author: "Anônimo" },
    { text: "Sonhe alto e trabalhe duro.", author: "Anônimo" },
    { text: "O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor é agora.", author: "Provérbio Chinês" },
    { text: "Tudo o que você sempre quis está do outro lado do medo.", author: "George Addair" },
    { text: "Dificuldades preparam pessoas comuns para destinos extraordinários.", author: "C.S. Lewis" },
    { text: "A imaginação é mais importante que o conhecimento.", author: "Albert Einstein" },
    { text: "Não conte os dias, faça os dias contarem.", author: "Muhammad Ali" },
    { text: "A jornada de mil milhas começa com um único passo.", author: "Lao Tsé" },
    { text: "Se você pode sonhar, você pode fazer.", author: "Walt Disney" },
    { text: "Foco é dizer não.", author: "Steve Jobs" },
    { text: "A prática leva à perfeição.", author: "Anônimo" },
    { text: "O aprendizado nunca esgota a mente.", author: "Leonardo da Vinci" },
    { text: "A inteligência é a habilidade de se adaptar à mudança.", author: "Stephen Hawking" },
    { text: "Conhecimento é poder.", author: "Francis Bacon" },
    { text: "O segredo de progredir é começar.", author: "Mark Twain" },
    { text: "Erros são prova de que você está tentando.", author: "Anônimo" },
    { text: "Não importa quão devagar você vá, desde que não pare.", author: "Confúcio" },
    { text: "A vitória pertence aos mais perseverantes.", author: "Napoleão Bonaparte" },
    { text: "O sucesso não é final, o fracasso não é fatal: o que conta é a coragem de continuar.", author: "Winston Churchill" },
    { text: "Sempre parece impossível até que seja feito.", author: "Nelson Mandela" },
    { text: "Mire na lua. Mesmo que você erre, cairá entre as estrelas.", author: "Norman Vincent Peale" },
    { text: "A melhor maneira de prever o futuro é inventá-lo.", author: "Alan Kay" },
    { text: "Seja grato pelo que você tem enquanto trabalha pelo que você quer.", author: "Anônimo" },
    { text: "Sua mente é seu maior patrimônio.", author: "Anônimo" },
    { text: "Pequenos passos todos os dias levam a grandes resultados.", author: "Anônimo" },
    { text: "A programação não é sobre o que você sabe; é sobre o que você pode descobrir.", author: "Chris Pine" },
    { text: "Não se compare com os outros, compare-se com quem você era ontem.", author: "Anônimo" },
    { text: "A sorte favorece os audazes.", author: "Virgílio" },
    { text: "Quem tem um 'porquê' enfrenta qualquer 'como'.", author: "Viktor Frankl" },
    { text: "Escreva código para humanos primeiro, para máquinas depois.", author: "Anônimo" },
    { text: "O maior erro que você pode cometer é o medo de cometer um.", author: "Elbert Hubbard" },
    { text: "A genialidade é 1% inspiração e 99% transpiração.", author: "Thomas Edison" },
    { text: "Seja humilde para aprender e ousado para aplicar.", author: "Anônimo" },
    { text: "A vida é o que acontece enquanto você faz outros planos.", author: "John Lennon" },
    { text: "Onde há vontade, há um caminho.", author: "Provérbio Inglês" },
    { text: "Não sabendo que era impossível, ele foi lá e fez.", author: "Jean Cocteau" },
    { text: "O conhecimento quando compartilhado é multiplicado.", author: "Anônimo" },
    { text: "Desafios são o que tornam a vida interessante.", author: "Joshua J. Marine" },
    { text: "Você não precisa ser grande para começar, mas precisa começar para ser grande.", author: "Zig Ziglar" },
    { text: "O que você faz hoje pode melhorar todos os seus amanhãs.", author: "Ralph Marston" },
    { text: "Aprenda como se fosse viver para sempre.", author: "Mahatma Gandhi" },
    { text: "Se você quer chegar onde a maioria não chega, faça o que a maioria não faz.", author: "Anônimo" },
    { text: "A paciência é amarga, mas seu fruto é doce.", author: "Jean-Jacques Rousseau" },
    { text: "Tudo o que a mente humana pode conceber e acreditar, ela pode alcançar.", author: "Napoleon Hill" },
    { text: "A maior glória não reside em nunca cair, mas em levantar-se cada vez que caímos.", author: "Confúcio" },
    { text: "Quanto mais eu treino, mais sorte eu tenho.", author: "Gary Player" },
    { text: "O sucesso é caminhar de fracasso em fracasso sem perder o entusiasmo.", author: "Winston Churchill" },
    { text: "Não espere o momento perfeito. Pegue o momento e torne-o perfeito.", author: "Anônimo" },
    { text: "Lembre-se de por que você começou.", author: "Anônimo" },
    { text: "O destino não é uma questão de sorte, é uma questão de escolha.", author: "William Jennings Bryan" },
    { text: "Faça o que você pode, com o que você tem, onde você está.", author: "Theodore Roosevelt" },
    { text: "Não há atalhos para os lugares onde vale a pena chegar.", author: "Beverly Sills" },
    { text: "Quem estuda, tem em suas mãos o poder de transformar o mundo.", author: "Anônimo" },
    { text: "A cada dia, um código melhor.", author: "Anônimo" },
    { text: "O esforço de hoje é o sucesso de amanhã.", author: "Anônimo" },
    { text: "Seja o protagonista da sua própria história.", author: "Anônimo" },
    { text: "A sabedoria começa na reflexão.", author: "Sócrates" },
    { text: "Não deixe o barulho das opiniões alheias abafar sua voz interior.", author: "Steve Jobs" },
    { text: "A inovação distingue um líder de um seguidor.", author: "Steve Jobs" },
    { text: "Seja resiliente.", author: "Anônimo" },
    { text: "Sua motivação é o que te faz começar, seu hábito é o que te faz continuar.", author: "Jim Ryun" },
    { text: "Se você está atravessando um inferno, continue indo.", author: "Winston Churchill" },
    { text: "A única pessoa que você deve tentar ser melhor do que é a pessoa que você foi ontem.", author: "Anônimo" },
    { text: "A educação é a arma mais poderosa que você pode usar para mudar o mundo.", author: "Nelson Mandela" },
    { text: "Acredite que você pode e você já está no meio do caminho.", author: "Theodore Roosevelt" },
    { text: "A melhor maneira de começar é parar de falar e começar a fazer.", author: "Walt Disney" },
    { text: "O sucesso não é o segredo da felicidade, a felicidade é o segredo do sucesso.", author: "Albert Schweitzer" },
    { text: "Se você quer algo que nunca teve, precisa fazer algo que nunca fez.", author: "Thomas Jefferson" },
    { text: "A felicidade não é algo pronto. Ela vem de suas próprias ações.", author: "Dalai Lama" },
    { text: "Vencer a si próprio é a maior das vitórias.", author: "Platão" },
    { text: "Para ser um mestre, você deve ser eterno aprendiz.", author: "Anônimo" },
    { text: "O trabalho duro supera o talento quando o talento não trabalha duro.", author: "Tim Notke" },
    { text: "Não limite seus desafios, desafie seus limites.", author: "Anônimo" },
    { text: "A maior aventura que você pode viver é a de viver a vida dos seus sonhos.", author: "Oprah Winfrey" },
    { text: "Mude seus pensamentos e você mudará seu mundo.", author: "Norman Vincent Peale" },
    { text: "O que não nos mata, nos torna mais fortes.", author: "Friedrich Nietzsche" },
    { text: "Simplicidade é a sofisticação máxima.", author: "Leonardo da Vinci" },
    { text: "A lógica leva você de A a B. A imaginação leva você a qualquer lugar.", author: "Albert Einstein" },
    { text: "Grandes mentes discutem ideias; mentes médias discutem eventos; mentes pequenas discutem pessoas.", author: "Eleanor Roosevelt" },
    { text: "O pessimista vê dificuldade em cada oportunidade; o otimista vê oportunidade em cada dificuldade.", author: "Winston Churchill" },
    { text: "Dê o seu melhor todos os dias, mesmo que o seu melhor não seja perfeito.", author: "Anônimo" },
    { text: "Não pare quando estiver cansado. Pare quando tiver terminado.", author: "Anônimo" },
    { text: "O conhecimento é o único tesouro que ninguém pode tirar de você.", author: "Anônimo" },
    { text: "Programar é a arte de organizar o caos.", author: "Anônimo" },
    { text: "Amanhã é a primeira folha em branco de um livro de 365 páginas. Escreva bem.", author: "Brad Paisley" }
];

function setRandomQuote() {
    let lastIndex = localStorage.getItem('lastQuoteIndex');

    let randomIndex;
    do {
        randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
    } while (randomIndex == lastIndex);

    localStorage.setItem('lastQuoteIndex', randomIndex);

    const quote = motivationalQuotes[randomIndex];

    document.querySelector('.quote-text').textContent = `"${quote.text}"`;
    document.querySelector('.quote-author').textContent = `- ${quote.author}`;
}

// Executa ao carregar a página
document.addEventListener('DOMContentLoaded', setRandomQuote);